# A hivatalos Jenkins LTS image-ből indul.
FROM jenkins/jenkins:lts
# Átvált root userre, hogy tudjon csomagokat telepíteni.
USER root
# Felteszi a szükséges csomagokat
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    sqlite3 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# A végén visszaáll a Jenkins felhasználóra.
USER jenkins
